### ISSUE TITLE
design a script format which allows easily convert to python code

### ISSUE THREAD

**Issue by LeoJhonSong** [RTCS-Team25/Project#13]

**Comment by LeoJhonSong** [comment]
Guys, check if this is feasible:

Since we are mainly doing conversations, we could regard our program as a **state machine switching between sentences**, and we use answer from the user or other reactions as the trigger to jump to another state. Therefore, the state table (conversation script) and the code could be seperated.
I suggest @maiahely create conversation script file with [**json** format](https://en.wikipedia.org/wiki/JSON#Example), and @mlsalloum and @MarkMain99 could simply load that file into our python code and switch between sentences based on user's answer. Here is a demo:

script.json written by **Maia**:
```json
{
    "1": {  // id of sentence
        "content": "hi",
        "next": [  // id of next sentence based on conditions
            "2", // if greeted
        ]
    },
    "2": {
        "content": "ok",
        "next": [
            "1"
        ]
    }
}
```

conversation.py written by **Maliik** and **Mark**:
```python
import jstyleson

# load script from the file
with open('./script.json') as f:
    data = jstyleson.load(f)

state = '1'

while True:
    tts.say(data[state]['content'])
    if state == '1' or state == '2':
        feedback = is_greedted()  # detect if user greeted back, if yes, is_greeted returns 0
    if state == ...:
        ...
    state = data[state]['next'][feedback]  # switch state of conversation
```

Instead of python's buildin json parsing module, the python module **jsyleson** supports to parse json file with comments and trailing commas (which are actually not originally supported by json syntax), so Maia could explain conditions of each option in the `'next'` segment.

Besides, this format also allows us to extend to other actions easily, by adding a segment `'action'` or something.

How do you guys think?

**Comment by mlsalloum** [comment]
From what you're saying it sounds like this approach will make it easier to implement tablet functionality as opposed to just a sequential program. I'm not familiar with this style of coding personally so I can look into it.

**Comment by LeoJhonSong** [comment]
> From what you're saying it sounds like this approach will make it easier to implement tablet functionality

I think it could also reduce the difficulty of implementation of the conversation 😄

**Comment by maiahely** [comment]
I think this is a very nice solution

**Comment by maiahely** [comment]
I will change the conversation format this weekend

**Comment by LeoJhonSong** [comment]
@maiahely as I've studied [your script](https://github.com/RTCS-Team25/Project/issues/4#issuecomment-713104313), actually we do not care what the user really said right? The only thing we need to do is to **judge is the user's answer positive or negative**. so maybe we can make an agreement that **the first item in the `next` segment is for positive answer, and the second item is for negative answer.**

**Comment by LeoJhonSong** [comment]
So we are actually already on aim2 now :+1: I think it is enough for aim1, so I'll close the aim1 epic.

**Comment by maiahely** [comment]
`{
    "1": {  // id of sentence
        "content": "Hi",
        "next": [  // id of next sentence based on conditions
            "2", // if greeted
        ]
    },
    "2": {
        "content": "Hello, how are you?",
        "next": [
            "3", //if response_positive
            "4", //if response_negative
        ]
    }
     "3": {
        "content": "Yay I am happy to hear that",
        "next": [
            "99"
        ]
    }
    "4": {
        "content": "I'm sorry to hear that, Can I help you feel better?",
        "next": [
            "5", //if response_positive
            "99", //if response_negative
        ]
    }
     "5": {
        "content": "Would you like to try some meditation with me?",
        "next": [
             "6", //if response_positive
            "99", //if response_negative
        ]
     "6": {
        "content": "Great, let's get started. Take a deep breath in and as you breathe out, look at my tablet",
        "next": [
             "7", //if response_positive
            "99", //if response_negative
        ]
    
    "n-2": {
        "content": "Can you tell me more?",
        "next": [
            "1"
        ]
    }
    "n-1": {
        "content": "i'm sorry i didn't get that, could you repeat?",
        "next": [
            "1"
        ]
    }
    
    "99": {
        "content": "Ok, have a nice day, take care of yourself.",
        
    }
`}``

**Comment by maiahely** [comment]
`{
    "1": {  // id of sentence
        "content": "Hi",
        "next": [  // id of next sentence based on conditions
            "2", // if greeted
        ]
    },
    "2": {
        "content": "Hello, how are you?",
        "next": [
            "3", //if response_positive
            "4", //if response_negative
        ]
    }
     "3": {
        "content": "Yay I am happy to hear that",
        "next": [
            "99"
        ]
    }
    "4": {
        "content": "I'm sorry to hear that, Can I help you feel better?",
        "next": [
            "5", //if response_positive
            "99", //if response_negative
        ]
    }
     "5": {
        "content": "Would you like to try some meditation with me?",
        "next": [
             "6", //if response_positive
            "99", //if response_negative
        ]
     "6": {
        "content": "Great, let's get started. Take a deep breath in and as you breathe out, look at my tablet",
        "next": [
             "7", //if response_positive
            "99", //if response_negative
        ]
    
    "n-2": {
        "content": "Can you tell me more?",
        "next": [
            "1"
        ]
    }
    "n-1": {
        "content": "i'm sorry i didn't get that, could you repeat?",
        "next": [
            "1"
        ]
    }
    
    "99": {
        "content": "Ok, have a nice day, take care of yourself.",
        
    }
}`

**Comment by maiahely** [comment]
Hi, I'm not quite sure why the code is formatting like this in the snippet above. But here is a sample that I wanted to check. As you can see in most states, I have added two options for a positive or negative response. Is this required or is that work already done by Mark and Malik's code?
