### ISSUE TITLE
convert script to json format

### ISSUE THREAD

**Issue by LeoJhonSong** [RTCS-Team25/Project#14]
format discussed in #13

**Comment by maiahely** [comment]
```{
    "1": {  // id of sentence
        "content": "Hi",
        "next": [  // id of next sentence based on conditions
            "2", // if greeted
        ]
    },
    "2": {
        "content": "Hello, how are you?",
        "next": [
            "3", //if response_positive
            "4", //if response_negative
        ]
    }
     "3": {
        "content": "Yay I am happy to hear that",
        "next": [
            "99"
        ]
    }
    "4": {
        "content": "I'm sorry to hear that, Can I help you feel better?",
        "next": [
            "5", //if response_positive
            "99", //if response_negative
        ]
    }
     "5": {
        "content": "Would you like to try some meditation with me?",
        "next": [
             "6", //if response_positive
            "99", //if response_negative
        ]
     "6": {
        "content": "Great, let's get started. Take a deep breath in and as you breathe out, look at my tablet",
        "next": [
             "7", //if response_positive
            "99", //if response_negative
        ]
    
    "n-2": {
        "content": "Can you tell me more?",
        "next": [
            "1"
        ]
    }
    "n-1": {
        "content": "i'm sorry i didn't get that, could you repeat?",
        "next": [
            "1"
        ]
    }
    
    "99": {
        "content": "Ok, have a nice day, take care of yourself.",
        
    }
}```

**Comment by maiahely** [comment]
Hi, I'm not quite sure why the code is formatting like this in the snippet above. But here is a sample that I wanted to check. As you can see in most states, I have added two options for a positive or negative response. Is this required or is that work already done by Mark and Malik's code?

**Comment by LeoJhonSong** [comment]
Exactly! Your code is rendered like that because you should use \`\`\` instead of \`\` to wrap code longer than one line. \`\` is just for inline code :smile: Besides, I suggest you type the code in an editor like VSC. It is very easy to forget a closing bracket without the help of a powerful editor. Also, you need to put comma at the end of a element as long as it is not the last element.

**Comment by LeoJhonSong** [comment]
> I have added two options for a positive or negative response. Is this required or is that work already done by Mark and Malik's code?

I suppose you do not need to comment normally. We could make an agreement that when there's not comments, the first one is for positive answer and the second one is for negative answer.

**Comment by LeoJhonSong** [comment]
@mlsalloum Hi, malik. I suppose you could now start to work on #12 as we already set down the format of the script.
