### ISSUE TITLE
Unclear situation won't be reached

### ISSUE THREAD

**Issue by LeoJhonSong** [RTCS-Team25/Project#16]
@maiahely During experiment I noticed that actually there will not be a situation that pepper get unclear response, or let's say we do not suppot to judge if the respoense is clear or not right now. We could do the judgement based on the possibility of the phrase given by pepper or by other meanings.

How do you think?

**Comment by maiahely** [comment]
That is interesting to hear. The unclear response I suppose would perhaps come into play in a noisy environment when the audio input wasn't so clear. However if you think it is unnecessary I can easily remove this or comment it out for now.
