### ISSUE TITLE
Debug of conversation

### ISSUE THREAD

**Issue by maiahely** [RTCS-Team25/Project#17]
I have re-committed the Pepper Json file in the conversation branch of Github (hopefully I've done this right). Changes to note;

State 5 should default to State 6 unless there is a negative response. i.e. a positive response OR no response will lead from State 5 to State 6. Looking at the code, I’m not quite sure how we would change that for this specific case as the function is_positive is applied to all states.

I have changed the meditation counting to sentences (One. Two. Three…) and we can simulate how Pepper will say this. If this does not work then we can try creating individual states for each number count.

I have changed the language in State 6 to say, “as you breathe in, close your eyes” instead of “as you breathe in, look at my tablet” until we have confirmation of what we will be able to produce on the tablet.

I have removed State 97 (case of unclear response) as it was decided that this did not actually happen in the lab.

**Comment by mlsalloum** [comment]
I'm making headway with displaying a breathing gif to follow along with for state 6 (I think) so if that works we could get rid of the counting all together and hard code a reasonable delay for the user to follow along?

**Comment by mlsalloum** [comment]
Also with regards to a neutral response there's currently no ability to discern neutral phrases, "okay" is listed in positive but I can look into modifying the code if that's useful
