### ISSUE TITLE
Search and design possible phrases and corresponding response

### ISSUE THREAD

**Issue by LeoJhonSong** [RTCS-Team25/Project#4]

**Comment by maiahely** [comment]
[https://app.zenhub.com/files/302626383/b14bebee-c9d5-4357-88ec-189769410708/download](https://app.zenhub.com/files/302626383/b14bebee-c9d5-4357-88ec-189769410708/download)

**Comment by LeoJhonSong** [comment]
![image](https://user-images.githubusercontent.com/37630203/96637667-9485af80-1351-11eb-89ed-08ed8ed54fa4.png)

**Comment by LeoJhonSong** [comment]
Hi Maia, is this conversation designed for the final output of this project or is this just for aim1 (or aim2), and we will have something else for the final output?

**Comment by maiahely** [comment]
This is an initial conversation that I would like to try. I think we would need to discuss with the group where to go from here as further complexity will involve more integration with the other tasks for example with the screen, or could have many many branches of conversation which could be too labour intensive to program for this project.

**Comment by LeoJhonSong** [comment]
Alright. So if this is for aim1, I suggest removing the usage of tablet, just focus on conversations. I will think of a format for you to note the conversation which allows to be converted to python code easily.
